### 1. Lấy tất cả danh sách đơn hàng (GET)
GET http://127.0.0.1:8000/orders

###
DELETE http://127.0.0.1:8000/orders/101

###
DELETE http://127.0.0.1:8000/orders/102

###
DELETE http://127.0.0.1:8000/orders/999